########
#
# Run from git root's parent: with .env in local folder and ProjectDomino/ inside
#
# $ touch .env
# $ sudo docker-compose -f ./ProjectDomino/infra/pipelines/docker/docker-compose.yml up -d prefect-agent
#
########

version: '3'

services:
  data-stream:
      build:
        context: ../../../
        dockerfile: infra/pipelines/docker/datastream-Dockerfile
      tty: true
      network_mode: 'bridge'
      #command: sh -c "pwd && ls && service tor start && python3 /app/search_by_date_job.py"
      volumes:
        - /home/codywebb/ProjectDomino/infra/pipelines/docker/jobs/neo4jcreds.json:/secrets/neo4jcreds.json:ro
      environment:
        PREFECT__SERVER__HOST: ${PREFECT__SERVER__HOST:-http://host.docker.internal}
        PREFECT__SERVER__PORT: ${PREFECT__SERVER__PORT:-4200}
        PREFECT__SERVER__UI__HOST: ${PREFECT__SERVER__UI__HOST:-http://host.docker.internal}
        PREFECT__SERVER__UI__PORT: ${PREFECT__SERVER__UI__PORT:-8080}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      logging:
        options:
          tag: 'ImageName:{{.ImageName}}/Name:{{.Name}}/ID:{{.ID}}/ImageFullID:{{.ImageFullID}}'
